"""
Django settings for kernelCI project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import sys
import threading
from utils.validation import is_boolean_or_string_true
from utils.development_metrics import start_development_metrics_server
import os
import json


def get_json_env_var(name, default):
    var = os.environ.get(name)
    if not var:
        return default
    try:
        return json.loads(var)
    except json.JSONDecodeError:
        if isinstance(default, str) or isinstance(default, bool):
            return var
        raise


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Path of data directory
BACKEND_DATA_DIR = os.path.join(BASE_DIR, "data")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_json_env_var(
    "DJANGO_SECRET_KEY", "django-insecure--!70an0r@i00)oqf!3uq_)9dx2^%)"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = is_boolean_or_string_true(os.environ.get("DEBUG", False))

DEBUG_SQL_QUERY = is_boolean_or_string_true(os.environ.get("DEBUG_SQL_QUERY", False))

# SECURITY WARNING: DO NOT PRINT PRODUCTION DB VARS
DEBUG_DB_VARS = is_boolean_or_string_true(os.environ.get("DEBUG_DB_VARS", False))

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 31536000

# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "kernelCI_app",
    "kernelCI_cache",
    "rest_framework",
    "drf_spectacular",
    "django_crontab",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "kernelCI_app.middleware.logServerErrorMiddleware.LogServerErrorMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "kernelCI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kernelCI.wsgi.application"

REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "KernelCI Dashboard API",
    "DESCRIPTION": "API for the KernelCI dashboard",
    "VERSION": "0.9.0",
}

# To run cronjobs locally, execute
# poetry run ./manage.py crontab arg
# where "arg" is add, remove or show
SKIP_CRONJOBS = is_boolean_or_string_true(os.environ.get("SKIP_CRONJOBS", False))
if SKIP_CRONJOBS:
    CRONJOBS = []
else:
    CRONJOBS = [
        ("0 * * * *", "kernelCI_app.tasks.update_checkout_cache"),
        (
            "59 * * * *",
            "django.core.management.call_command",
            [
                "notifications",
                "--action=new_issues",
                "--to=kernelci-results@groups.io",
                "--cc=gus@collabora.com",
                "--send",
                "--yes",
            ],
        ),
        (
            "30 14 * * *",
            "django.core.management.call_command",
            [
                "notifications",
                "--action=summary",
                "--to=kernelcialerts@microsoft.com",
                "--cc=kernelci-results@groups.io",
                "--ignore-recipients",
                "--send",
                "--yes",
                "--summary-origins=microsoft",
            ],
        ),
        (
            "30 2 * * *",
            "django.core.management.call_command",
            [
                "notifications",
                "--action=summary",
                "--add-mailing-lists",
                "--send",
                "--yes",
                "--summary-origins=maestro",
            ],
        ),
        (
            "33 3 * * 1",
            "django.core.management.call_command",
            [
                "notifications",
                "--action=hardware_summary",
                "--cc=kernelci-results@groups.io",
                "--send",
                "--yes",
            ],
        ),
        (
            "0 0 * * 1",
            "django.core.management.call_command",
            [
                "delete_unused_hardware_status",
            ],
        ),
        (
            "0 0 * * 6",
            "django.core.management.call_command",
            [
                "notifications",
                "--action=metrics_summary",
                "--to=kernelci@lists.linux.dev",
                "--cc=kernelci-results@groups.io",
                "--send",
                "--yes",
            ],
        ),
    ]

# Email settings for SMTP backend
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = os.environ.get("EMAIL_PORT", 587)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "bot@kernelci.org")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# When running on docker it won't build without this variable,
# the default value here is for when running locally
BACKEND_VOLUME_DIR = os.environ.get("BACKEND_VOLUME_DIR", "volume_data")

DATABASE_ROUTERS = ["kernelCI_app.routers.databaseRouter.DatabaseRouter"]

# Database definition configurations
kcidb_config = get_json_env_var(
    "DB_DEFAULT",
    {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": "kernelci",
        "USER": "kernelci",
        "PASSWORD": "kernelci-db-password",
        "HOST": "127.0.0.1",
        "OPTIONS": {
            "connect_timeout": 16,
        },
    },
)

dashboard_db_config = {
    "ENGINE": "django_prometheus.db.backends.postgresql",
    "NAME": os.environ.get("DASH_DB_NAME", "dashboard"),
    "USER": os.environ.get("DASH_DB_USER", "dev"),
    "PASSWORD": os.environ.get("DASH_DB_PASSWORD", "dev"),
    "HOST": os.environ.get("DASH_DB_HOST", "127.0.0.1"),
    "PORT": os.environ.get("DASH_DB_PORT", 5434),
    "OPTIONS": {
        "connect_timeout": 16,
    },
}

# Common databases
cache_db_config = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": os.path.join(BACKEND_VOLUME_DIR, "cache.sqlite3"),
}

notifications_db_config = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": os.path.join(BACKEND_VOLUME_DIR, "notifications.sqlite3"),
}

USE_DASHBOARD_DB = is_boolean_or_string_true(os.environ.get("USE_DASHBOARD_DB", False))
if USE_DASHBOARD_DB:
    DATABASES = {
        "default": dashboard_db_config,
        "kcidb": kcidb_config,
        "cache": cache_db_config,
        "notifications": notifications_db_config,
    }
else:
    DATABASES = {
        "default": kcidb_config,
        "dashboard_db": dashboard_db_config,
        "cache": cache_db_config,
        "notifications": notifications_db_config,
    }

if DEBUG_DB_VARS:
    print("DEBUG: DATABASES:", DATABASES)


REDIS_HOST = os.environ.get("REDIS_HOST", "127.0.0.1")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:6379",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIGRATION_MODULES = {
    "kernelCI_app": "kernelCI_app.migrations",
    "kernelCI_cache": "kernelCI_cache.migrations",
}

CORS_ALLOWED_ORIGINS = get_json_env_var(
    "CORS_ALLOWED_ORIGINS",
    [],
)
CORS_ALLOW_ALL_ORIGINS = is_boolean_or_string_true(
    os.environ.get("CORS_ALLOW_ALL_ORIGINS", False)
)

CACHE_TIMEOUT = int(os.environ.get("CACHE_TIMEOUT", "180"))

if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost",  # dashboard dev server
    ]
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 3600
    CACHE_TIMEOUT = 0


# Base logging configuration. Individual loggers must be set in order to log messages.
LOGGING = {
    "disable_existing_loggers": False,
    "version": 1,
    "handlers": {
        "console": {
            # logging handler that outputs log messages to terminal
            "class": "logging.StreamHandler",
            "level": "DEBUG",  # message level to be written to console
        },
    },
}

# this sets root level logger to log debug and higher level
# logs to console. All other loggers inherit settings from
# root level logger.
ENABLE_LOGGING = is_boolean_or_string_true(os.environ.get("ENABLE_LOGGING", False))
if ENABLE_LOGGING:
    LOGGING["loggers"] = {
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,  # this tells logger to send logging message
            # to its parent (will send if set to True)
        },
    }

if DEBUG_SQL_QUERY:
    if LOGGING.get("loggers") is None:
        # No other logger set, only db logs
        LOGGING["loggers"] = {
            "django.db": {
                "handlers": ["console"],
                "level": "DEBUG",
            }
        }
    else:
        # Adds database logging
        LOGGING["loggers"]["django.db"] = {"level": "DEBUG"}

DEFAULT_ORIGIN_LISTING_INTERVAL_IN_DAYS = int(
    os.environ.get("DEFAULT_ORIGIN_LISTING_INTERVAL_IN_DAYS", 30)
)

PROMETHEUS_METRICS_ENABLED = is_boolean_or_string_true(
    os.environ.get("PROMETHEUS_METRICS_ENABLED", False)
)

if PROMETHEUS_METRICS_ENABLED:
    # Local development
    if "runserver" in sys.argv:
        print("Starting development metrics server")
        # The '--noreload' is important, otherwise Django will start two processes
        metrics_thread = threading.Thread(
            target=start_development_metrics_server, daemon=True
        )
        metrics_thread.start()

base_allowed_hosts = ["localhost"]

if DEBUG and PROMETHEUS_METRICS_ENABLED:
    base_allowed_hosts.append("0.0.0.0")
    base_allowed_hosts.append("host.docker.internal")

ALLOWED_HOSTS = get_json_env_var(
    "ALLOWED_HOSTS",
    base_allowed_hosts,
)
