DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{{DASHBOARD_DB_USER}}') THEN
        CREATE ROLE "{{DASHBOARD_DB_USER}}" LOGIN PASSWORD '{{DB_PASSWORD}}';
    ELSE
        ALTER ROLE "{{DASHBOARD_DB_USER}}" WITH LOGIN PASSWORD '{{DB_PASSWORD}}';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{{APP_DB_USER}}') THEN
        CREATE ROLE "{{APP_DB_USER}}" LOGIN PASSWORD '{{DB_PASSWORD}}';
    ELSE
        ALTER ROLE "{{APP_DB_USER}}" WITH LOGIN PASSWORD '{{DB_PASSWORD}}';
    END IF;
END
$$;

SELECT format('CREATE DATABASE %I OWNER %I', '{{DASHBOARD_DB}}', '{{DASHBOARD_DB_USER}}')
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{DASHBOARD_DB}}')
\gexec

SELECT format('CREATE DATABASE %I OWNER %I', '{{APP_DB}}', '{{APP_DB_USER}}')
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{APP_DB}}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE "{{DASHBOARD_DB}}" TO "{{DASHBOARD_DB_USER}}";
GRANT ALL PRIVILEGES ON DATABASE "{{APP_DB}}" TO "{{APP_DB_USER}}";
