DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{{DB_USER}}') THEN
        CREATE ROLE "{{DB_USER}}" LOGIN PASSWORD '{{DB_PASSWORD}}';
    ELSE
        ALTER ROLE "{{DB_USER}}" WITH LOGIN PASSWORD '{{DB_PASSWORD}}';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{{APP_DB_USER}}') THEN
        CREATE ROLE "{{APP_DB_USER}}" LOGIN PASSWORD '{{DB_PASSWORD}}';
    ELSE
        ALTER ROLE "{{APP_DB_USER}}" WITH LOGIN PASSWORD '{{DB_PASSWORD}}';
    END IF;
END
$$;

SELECT format('CREATE DATABASE %I OWNER %I', '{{DB_NAME}}', '{{DB_USER}}')
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{DB_NAME}}')
\gexec

SELECT format('CREATE DATABASE %I OWNER %I', '{{APP_DB}}', '{{APP_DB_USER}}')
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{APP_DB}}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE "{{DB_NAME}}" TO "{{DB_USER}}";
GRANT ALL PRIVILEGES ON DATABASE "{{APP_DB}}" TO "{{APP_DB_USER}}";
