#!/usr/bin/env sh

poetry run ruff format --check .
FORMAT_STATUS=$?

if [ $FORMAT_STATUS -ne 0 ]; then
  exit 1
fi

poetry run ruff check .
LINT_STATUS=$?

if [ $LINT_STATUS -ne 0 ]; then
  exit 1
fi

exit 0
