# Generated by Django 5.1.7 on 2025-04-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckoutsCache",
        ),
    ]
