# Generated by Django 5.1.7 on 2025-04-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0003_recreate_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_done",
            new_name="done_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_done",
            new_name="done_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_done",
            new_name="done_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_error",
            new_name="error_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_error",
            new_name="error_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_error",
            new_name="error_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_fail",
            new_name="fail_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_fail",
            new_name="fail_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_fail",
            new_name="fail_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_miss",
            new_name="miss_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_miss",
            new_name="miss_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_miss",
            new_name="miss_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_null",
            new_name="null_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_null",
            new_name="null_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_null",
            new_name="null_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_pass",
            new_name="pass_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_pass",
            new_name="pass_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_pass",
            new_name="pass_tests",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="boot_skip",
            new_name="skip_boots",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="build_skip",
            new_name="skip_builds",
        ),
        migrations.RenameField(
            model_name="checkoutscache",
            old_name="test_skip",
            new_name="skip_tests",
        ),
    ]
