# Generated by Django 5.1.7 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0004_rename_count_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutscache",
            name="origin_builds_finish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutscache",
            name="origin_tests_finish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
