# Generated by Django 5.1.8 on 2025-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0007_refresh_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationsCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.TextField()),
                ("notification_sent", models.DateTimeField()),
                ("checkout_id", models.TextField()),
            ],
            options={
                "db_table": "notifications_checkout",
            },
        ),
    ]
