# Generated by Django 5.1.8 on 2025-05-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0008_notificationscheckout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationscheckout",
            old_name="notification_id",
            new_name="notification_message_id",
        ),
    ]
