# Generated by Django 5.1.8 on 2025-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0009_rename_notification_id_to_notification_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationsIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_message_id", models.TextField(null=True)),
                ("notification_sent", models.DateTimeField(null=True)),
                ("issue_id", models.TextField()),
                ("issue_version", models.IntegerField()),
                ("issue_type", models.TextField(null=True)),
            ],
            options={
                "db_table": "notifications_issue",
                "unique_together": {("issue_id", "issue_version")},
            },
        ),
    ]
