# Generated by Django 5.1.8 on 2025-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_cache", "0010_notificationsissue"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuesCustom",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("version", models.IntegerField()),
                ("kcidb_timestamp", models.DateTimeField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("type", models.TextField(null=True)),
                ("notification_ignore", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "issues_custom",
                "unique_together": {("id", "version")},
            },
        ),
    ]
