# Generated by Django 5.2.11 on 2026-06-03 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_cache", "0012_add_checkout_report_identification_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckoutsCache",
        ),
    ]
