# Generated by Django 5.1.10 on 2025-09-10 16:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0002_remove_fk_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="builds",
            name="series",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.MD5(
                    django.db.models.functions.text.Concat(
                        models.F("config_name"),
                        models.F("compiler"),
                        models.F("architecture"),
                    )
                ),
                output_field=models.TextField(blank=True, null=True),
            ),
        ),
        migrations.AddIndex(
            model_name="builds",
            index=models.Index(fields=["series"], name="builds_series_idx"),
        ),
    ]
