# Generated by Django 5.1.12 on 2025-09-11 18:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0003_add_build_series_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="series",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.MD5(
                    django.db.models.functions.text.Concat(
                        models.F("path"), models.F("environment_misc__platform")
                    )
                ),
                output_field=models.TextField(blank=True, null=True),
            ),
        ),
        migrations.AddIndex(
            model_name="tests",
            index=models.Index(fields=["series"], name="tests_series_idx"),
        ),
    ]
