# Generated by Django 5.2.8 on 2025-11-27 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0009_add_test_origin_start_time_platform_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTest",
            fields=[
                ("test_id", models.TextField(primary_key=True, serialize=False)),
                ("origin", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatible",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("build_id", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pass"), ("F", "Fail"), ("I", "Inconclusive")],
                        max_length=1,
                    ),
                ),
                ("is_boot", models.BooleanField()),
            ],
            options={
                "db_table": "pending_test",
            },
        ),
        migrations.CreateModel(
            name="HardwareStatus",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "test_origin",
                        "platform",
                        "checkout_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("test_origin", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("build_pass", models.IntegerField(default=0)),
                ("build_failed", models.IntegerField(default=0)),
                ("build_inc", models.IntegerField(default=0)),
                ("boot_pass", models.IntegerField(default=0)),
                ("boot_failed", models.IntegerField(default=0)),
                ("boot_inc", models.IntegerField(default=0)),
                ("test_pass", models.IntegerField(default=0)),
                ("test_failed", models.IntegerField(default=0)),
                ("test_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_status",
                "indexes": [
                    models.Index(
                        fields=["test_origin", "start_time"],
                        name="hw_status_origin_time",
                    ),
                    models.Index(fields=["checkout_id"], name="hw_status_checkout_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LatestCheckout",
            fields=[
                ("checkout_id", models.TextField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("origin", models.CharField(max_length=100)),
                ("tree_name", models.TextField(blank=True, null=True)),
                ("git_repository_url", models.TextField(blank=True, null=True)),
                ("git_repository_branch", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "latest_checkout",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origin",
                            "tree_name",
                            "git_repository_url",
                            "git_repository_branch",
                        ),
                        name="latest_checkout_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedHardwareStatus",
            fields=[
                (
                    "hardware_key",
                    models.BinaryField(
                        max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("checkout_id", models.TextField()),
            ],
            options={
                "db_table": "processed_hardware_status",
                "indexes": [
                    models.Index(fields=["checkout_id"], name="phs_checkout_id")
                ],
            },
        ),
    ]
