# Generated by Django 5.2.9 on 2025-12-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0010_add_hardware_denormalization_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestcheckout",
            name="checkout_id",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="latestcheckout",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="latestcheckout",
            index=models.Index(
                fields=["checkout_id"], name="latest_checkout_checkout_id"
            ),
        ),
    ]
