# Generated by Django 5.2.9 on 2025-12-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0011_modify_latest_checkout_primary_key"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProcessedHardwareStatus",
            new_name="ProcessedListingItems",
        ),
        migrations.RenameField(
            model_name="processedlistingitems",
            old_name="hardware_key",
            new_name="listing_item_key",
        ),
        migrations.AlterModelTable(
            name="processedlistingitems",
            table="processed_listing_items",
        ),
    ]
