# Generated by Django 5.2.9 on 2025-12-18 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0012_rename_processedhardwarestatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingBuilds",
            fields=[
                ("build_id", models.TextField(primary_key=True, serialize=False)),
                ("origin", models.CharField(max_length=100)),
                ("checkout_id", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pass"), ("F", "Fail"), ("I", "Inconclusive")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "pending_builds",
            },
        ),
        migrations.CreateModel(
            name="TreeListing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("checkout_id", models.TextField()),
                ("origin", models.TextField()),
                ("tree_name", models.TextField(blank=True, null=True)),
                ("git_repository_url", models.TextField(blank=True, null=True)),
                ("git_repository_branch", models.TextField(blank=True, null=True)),
                ("git_commit_hash", models.TextField(blank=True, null=True)),
                ("git_commit_name", models.TextField(blank=True, null=True)),
                (
                    "git_commit_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("build_pass", models.IntegerField(default=0)),
                ("build_failed", models.IntegerField(default=0)),
                ("build_inc", models.IntegerField(default=0)),
                ("boot_pass", models.IntegerField(default=0)),
                ("boot_failed", models.IntegerField(default=0)),
                ("boot_inc", models.IntegerField(default=0)),
                ("test_pass", models.IntegerField(default=0)),
                ("test_failed", models.IntegerField(default=0)),
                ("test_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tree_listing",
                "indexes": [
                    models.Index(fields=["start_time"], name="tree_listing_start_time"),
                    models.Index(
                        fields=["checkout_id"], name="tree_listing_checkout_id"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origin",
                            "tree_name",
                            "git_repository_url",
                            "git_repository_branch",
                        ),
                        name="tree_listing_tree_unique",
                    )
                ],
            },
        ),
    ]
