# Generated by Django 5.2.9 on 2026-01-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0013_pendingbuilds_treelisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedlistingitems",
            name="status",
            field=models.CharField(
                choices=[("P", "Pass"), ("F", "Fail"), ("I", "Inconclusive")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pendingbuilds",
            name="status",
            field=models.CharField(
                choices=[("P", "Pass"), ("F", "Fail"), ("I", "Inconclusive")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pendingtest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pass"), ("F", "Fail"), ("I", "Inconclusive")],
                max_length=1,
                null=True,
            ),
        ),
    ]
