# Generated by Django 5.2.9 on 2026-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0014_add_processed_and_pending_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingtest",
            name="platform",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
