# Generated by Django 5.2.9 on 2026-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0015_alter_pendingtest_platform"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="treelisting",
            name="tree_listing_tree_unique",
        ),
        migrations.AddConstraint(
            model_name="treelisting",
            constraint=models.UniqueConstraint(
                fields=(
                    "origin",
                    "tree_name",
                    "git_repository_url",
                    "git_repository_branch",
                    "git_commit_hash",
                ),
                name="tree_listing_tree_unique",
                nulls_distinct=False,
            ),
        ),
    ]
