# Generated by Django 5.2.11 on 2026-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0016_alter_treelisting_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="treelisting",
            name="new_field",
            field=models.TextField(blank=True, null=True),
        ),
    ]
