# Generated by Django 5.2.11 on 2026-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0016_alter_treelisting_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtest",
            name="full_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                    ("SKIP", "Skip"),
                    ("ERROR", "Error"),
                    ("MISS", "Miss"),
                    ("DONE", "Done"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingtest",
            name="lab",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingtest",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingtest",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TreeTestsRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.TextField()),
                ("tree_name", models.TextField(blank=True, null=True)),
                ("git_repository_branch", models.TextField(blank=True, null=True)),
                ("git_repository_url", models.TextField(blank=True, null=True)),
                ("git_commit_hash", models.TextField(blank=True, null=True)),
                ("path_group", models.TextField()),
                ("build_config_name", models.TextField()),
                ("build_architecture", models.TextField()),
                ("build_compiler", models.TextField()),
                ("hardware_key", models.TextField()),
                ("test_platform", models.TextField(blank=True, null=True)),
                ("test_lab", models.TextField(blank=True, null=True)),
                ("test_origin", models.TextField(blank=True, null=True)),
                ("issue_id", models.TextField(blank=True, null=True)),
                ("issue_version", models.IntegerField(blank=True, null=True)),
                ("issue_uncategorized", models.BooleanField(default=False)),
                ("is_boot", models.BooleanField(default=False)),
                ("pass_tests", models.IntegerField(default=0)),
                ("fail_tests", models.IntegerField(default=0)),
                ("skip_tests", models.IntegerField(default=0)),
                ("error_tests", models.IntegerField(default=0)),
                ("miss_tests", models.IntegerField(default=0)),
                ("done_tests", models.IntegerField(default=0)),
                ("null_tests", models.IntegerField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tree_tests_rollup",
                "indexes": [
                    models.Index(
                        fields=[
                            "origin",
                            "tree_name",
                            "git_repository_branch",
                            "git_repository_url",
                            "git_commit_hash",
                        ],
                        name="tree_tests_rollup_scope",
                    ),
                    models.Index(
                        fields=["path_group", "total_tests"],
                        name="tree_tests_rollup_group_total",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origin",
                            "tree_name",
                            "git_repository_branch",
                            "git_repository_url",
                            "git_commit_hash",
                            "path_group",
                            "build_config_name",
                            "build_architecture",
                            "build_compiler",
                            "hardware_key",
                            "test_platform",
                            "test_lab",
                            "test_origin",
                            "issue_id",
                            "issue_version",
                            "issue_uncategorized",
                        ),
                        name="tree_tests_rollup_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
