# Generated by Django 5.2.11 on 2026-05-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0017_add_tree_tests_rollup_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareRegistryPlatformVendor",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.CharField(default="platform_vendor", max_length=64)),
                ("url", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hardware_registry_platform_vendors",
            },
        ),
        migrations.CreateModel(
            name="HardwareRegistrySiliconVendor",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=64)),
                ("url", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hardware_registry_silicon_vendors",
            },
        ),
        migrations.CreateModel(
            name="HardwareRegistryProcessor",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.CharField(default="soc", max_length=64)),
                ("url", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("architecture", models.TextField(blank=True, null=True)),
                ("cores", models.IntegerField(blank=True, null=True)),
                ("max_clock_speed_mhz", models.IntegerField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_processors",
                        to="kernelCI_app.hardwareregistrysiliconvendor",
                    ),
                ),
            ],
            options={
                "db_table": "hardware_registry_processors",
            },
        ),
        migrations.CreateModel(
            name="HardwareRegistrySystemModule",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=64)),
                ("url", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("form_factor", models.TextField(blank=True, null=True)),
                (
                    "processor",
                    models.ForeignKey(
                        db_column="processor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_system_modules",
                        to="kernelCI_app.hardwareregistryprocessor",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_system_modules",
                        to="kernelCI_app.hardwareregistryplatformvendor",
                    ),
                ),
            ],
            options={
                "db_table": "hardware_registry_system_modules",
            },
        ),
        migrations.CreateModel(
            name="HardwareRegistryPlatform",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=64)),
                ("url", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("form_factor", models.TextField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_platforms",
                        to="kernelCI_app.hardwareregistryplatformvendor",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        db_column="processor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_platforms",
                        to="kernelCI_app.hardwareregistryprocessor",
                    ),
                ),
                (
                    "system_module",
                    models.ForeignKey(
                        blank=True,
                        db_column="system_module_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_registry_platforms",
                        to="kernelCI_app.hardwareregistrysystemmodule",
                    ),
                ),
            ],
            options={
                "db_table": "hardware_registry_platforms",
            },
        ),
    ]
