# Generated by Django 5.2.11 on 2026-07-31 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0018_hardwareregistryplatformvendor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareDailyBuilds",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "checkout_day",
                        "build_origin",
                        "build_lab",
                        "platform",
                        "checkout_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_day", models.DateField()),
                ("checkout_id", models.TextField()),
                ("build_origin", models.CharField(max_length=100)),
                ("build_lab", models.TextField()),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("build_pass", models.IntegerField(default=0)),
                ("build_failed", models.IntegerField(default=0)),
                ("build_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_daily_builds",
                "indexes": [
                    models.Index(
                        fields=["build_origin", "checkout_day"],
                        name="hw_daily_builds_org_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HardwareDailyTests",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "checkout_day",
                        "test_origin",
                        "test_lab",
                        "platform",
                        "checkout_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_day", models.DateField()),
                ("checkout_id", models.TextField()),
                ("test_origin", models.CharField(max_length=100)),
                ("test_lab", models.TextField()),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("boot_pass", models.IntegerField(default=0)),
                ("boot_failed", models.IntegerField(default=0)),
                ("boot_inc", models.IntegerField(default=0)),
                ("test_pass", models.IntegerField(default=0)),
                ("test_failed", models.IntegerField(default=0)),
                ("test_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_daily_tests",
                "indexes": [
                    models.Index(
                        fields=["test_origin", "checkout_day"],
                        name="hw_daily_tests_org_day",
                    )
                ],
            },
        ),
    ]
