# Generated by Django 5.2.11 on 2026-07-28 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0018_hardwareregistryplatformvendor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareBuildStatus",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "build_origin",
                        "build_lab",
                        "platform",
                        "checkout_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("build_origin", models.CharField(max_length=100)),
                ("build_lab", models.TextField()),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("build_pass", models.IntegerField(default=0)),
                ("build_failed", models.IntegerField(default=0)),
                ("build_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_build_status",
            },
        ),
        migrations.CreateModel(
            name="HardwareTestStatus",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "test_origin",
                        "test_lab",
                        "platform",
                        "checkout_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("test_origin", models.CharField(max_length=100)),
                ("test_lab", models.TextField()),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("boot_pass", models.IntegerField(default=0)),
                ("boot_failed", models.IntegerField(default=0)),
                ("boot_inc", models.IntegerField(default=0)),
                ("test_pass", models.IntegerField(default=0)),
                ("test_failed", models.IntegerField(default=0)),
                ("test_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_test_status",
            },
        ),
        migrations.DeleteModel(
            name="HardwareStatus",
        ),
        migrations.AddIndex(
            model_name="hardwarebuildstatus",
            index=models.Index(
                fields=["build_origin", "start_time"], name="hw_build_origin_time"
            ),
        ),
        migrations.AddIndex(
            model_name="hardwarebuildstatus",
            index=models.Index(fields=["checkout_id"], name="hw_build_checkout_id"),
        ),
        migrations.AddIndex(
            model_name="hardwareteststatus",
            index=models.Index(
                fields=["test_origin", "start_time"], name="hw_test_origin_time"
            ),
        ),
        migrations.AddIndex(
            model_name="hardwareteststatus",
            index=models.Index(fields=["checkout_id"], name="hw_test_checkout_id"),
        ),
    ]
