# Generated by Django 5.2.11 on 2026-06-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0018_hardwareregistryplatformvendor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "labs",
            },
        ),
        migrations.AddField(
            model_name="builds",
            name="lab",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="kernelCI_app.labs",
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="lab",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="kernelCI_app.labs",
            ),
        ),
    ]
