# Generated by Django 5.2.16 on 2026-09-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0020_add_labs_fk_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commits",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("git_commit_hash", models.TextField(unique=True)),
                ("author_name", models.TextField(blank=True, null=True)),
                ("author_email", models.TextField(blank=True, null=True)),
                ("author_date", models.DateTimeField(blank=True, null=True)),
                ("committer_name", models.TextField(blank=True, null=True)),
                ("committer_email", models.TextField(blank=True, null=True)),
                ("committer_date", models.DateTimeField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("fetched_from_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "commits",
            },
        ),
        migrations.CreateModel(
            name="CommitParents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ord", models.SmallIntegerField()),
                (
                    "commit",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_edges",
                        to="kernelCI_app.commits",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_edges",
                        to="kernelCI_app.commits",
                    ),
                ),
            ],
            options={
                "db_table": "commit_parents",
                "indexes": [
                    models.Index(fields=["parent"], name="commit_parents_parent_id"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("commit", "ord"),
                        name="commit_parents_commit_ord",
                    ),
                ],
            },
        ),
    ]
