# Generated by Django 5.2.16 on 2026-09-01 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0019_hardwaredailybuilds_hardwaredailytests"),
        ("kernelCI_app", "0020_add_labs_fk_indexes"),
    ]

    operations = []
