/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree/route'
import { Route as HardwareRouteImport } from './routes/hardware/route'
import { Route as IndexImport } from './routes/index'
import { Route as TreeIndexImport } from './routes/tree/index'
import { Route as HardwareIndexImport } from './routes/hardware/index'
import { Route as TreeTreeIdRouteImport } from './routes/tree/$treeId/route'
import { Route as TestTestIdRouteImport } from './routes/test/$testId/route'
import { Route as IssueIssueIdRouteImport } from './routes/issue/$issueId/route'
import { Route as HardwareHardwareIdRouteImport } from './routes/hardware/$hardwareId/route'
import { Route as BuildBuildIdRouteImport } from './routes/build/$buildId/route'
import { Route as alternativesTRouteImport } from './routes/(alternatives)/t/route'
import { Route as TreeTreeIdIndexImport } from './routes/tree/$treeId/index'
import { Route as TestTestIdIndexImport } from './routes/test/$testId/index'
import { Route as IssueIssueIdIndexImport } from './routes/issue/$issueId/index'
import { Route as HardwareHardwareIdIndexImport } from './routes/hardware/$hardwareId/index'
import { Route as BuildBuildIdIndexImport } from './routes/build/$buildId/index'
import { Route as alternativesTIndexImport } from './routes/(alternatives)/t/index'
import { Route as HardwareHardwareIdTestRouteImport } from './routes/hardware/$hardwareId/test/route'
import { Route as HardwareHardwareIdBuildRouteImport } from './routes/hardware/$hardwareId/build/route'
import { Route as HardwareHardwareIdBootRouteImport } from './routes/hardware/$hardwareId/boot/route'
import { Route as alternativesTTreeIdRouteImport } from './routes/(alternatives)/t/$treeId/route'
import { Route as TreeTreeNameBranchIndexImport } from './routes/tree/$treeName/$branch/index'
import { Route as HardwareHardwareIdTestIndexImport } from './routes/hardware/$hardwareId/test/index'
import { Route as HardwareHardwareIdBuildIndexImport } from './routes/hardware/$hardwareId/build/index'
import { Route as HardwareHardwareIdBootIndexImport } from './routes/hardware/$hardwareId/boot/index'
import { Route as alternativesTTreeIdIndexImport } from './routes/(alternatives)/t/$treeId/index'
import { Route as TreeTreeIdTestTestIdRouteImport } from './routes/tree/$treeId/test/$testId/route'
import { Route as TreeTreeIdTestTestIdIndexImport } from './routes/tree/$treeId/test/$testId/index'
import { Route as TreeTreeIdBuildBuildIdIndexImport } from './routes/tree/$treeId/build/$buildId/index'
import { Route as HardwareHardwareIdTestTestIdIndexImport } from './routes/hardware/$hardwareId/test/$testId/index'
import { Route as HardwareHardwareIdBuildBuildIdIndexImport } from './routes/hardware/$hardwareId/build/$buildId/index'
import { Route as HardwareHardwareIdBootBootIdIndexImport } from './routes/hardware/$hardwareId/boot/$bootId/index'
import { Route as alternativesTTreeNameBranchIndexImport } from './routes/(alternatives)/t/$treeName/$branch/index'
import { Route as alternativesTTreeIdTestTestIdRouteImport } from './routes/(alternatives)/t/$treeId/test/$testId/route'
import { Route as alternativesTTreeIdTestTestIdIndexImport } from './routes/(alternatives)/t/$treeId/test/$testId/index'
import { Route as alternativesTTreeIdBuildBuildIdIndexImport } from './routes/(alternatives)/t/$treeId/build/$buildId/index'

// Create/Update Routes

const TreeRouteRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRoute,
} as any)

const HardwareRouteRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TreeIndexRoute = TreeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreeRouteRoute,
} as any)

const HardwareIndexRoute = HardwareIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HardwareRouteRoute,
} as any)

const TreeTreeIdRouteRoute = TreeTreeIdRouteImport.update({
  id: '/$treeId',
  path: '/$treeId',
  getParentRoute: () => TreeRouteRoute,
} as any)

const TestTestIdRouteRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRoute,
} as any)

const IssueIssueIdRouteRoute = IssueIssueIdRouteImport.update({
  id: '/issue/$issueId',
  path: '/issue/$issueId',
  getParentRoute: () => rootRoute,
} as any)

const HardwareHardwareIdRouteRoute = HardwareHardwareIdRouteImport.update({
  id: '/$hardwareId',
  path: '/$hardwareId',
  getParentRoute: () => HardwareRouteRoute,
} as any)

const BuildBuildIdRouteRoute = BuildBuildIdRouteImport.update({
  id: '/build/$buildId',
  path: '/build/$buildId',
  getParentRoute: () => rootRoute,
} as any)

const alternativesTRouteRoute = alternativesTRouteImport.update({
  id: '/(alternatives)/t',
  path: '/t',
  getParentRoute: () => rootRoute,
} as any)

const TreeTreeIdIndexRoute = TreeTreeIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreeTreeIdRouteRoute,
} as any)

const TestTestIdIndexRoute = TestTestIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestTestIdRouteRoute,
} as any)

const IssueIssueIdIndexRoute = IssueIssueIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssueIssueIdRouteRoute,
} as any)

const HardwareHardwareIdIndexRoute = HardwareHardwareIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HardwareHardwareIdRouteRoute,
} as any)

const BuildBuildIdIndexRoute = BuildBuildIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildBuildIdRouteRoute,
} as any)

const alternativesTIndexRoute = alternativesTIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => alternativesTRouteRoute,
} as any)

const HardwareHardwareIdTestRouteRoute =
  HardwareHardwareIdTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => HardwareHardwareIdRouteRoute,
  } as any)

const HardwareHardwareIdBuildRouteRoute =
  HardwareHardwareIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => HardwareHardwareIdRouteRoute,
  } as any)

const HardwareHardwareIdBootRouteRoute =
  HardwareHardwareIdBootRouteImport.update({
    id: '/boot',
    path: '/boot',
    getParentRoute: () => HardwareHardwareIdRouteRoute,
  } as any)

const alternativesTTreeIdRouteRoute = alternativesTTreeIdRouteImport.update({
  id: '/$treeId',
  path: '/$treeId',
  getParentRoute: () => alternativesTRouteRoute,
} as any)

const TreeTreeNameBranchIndexRoute = TreeTreeNameBranchIndexImport.update({
  id: '/$treeName/$branch/',
  path: '/$treeName/$branch/',
  getParentRoute: () => TreeRouteRoute,
} as any)

const HardwareHardwareIdTestIndexRoute =
  HardwareHardwareIdTestIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HardwareHardwareIdTestRouteRoute,
  } as any)

const HardwareHardwareIdBuildIndexRoute =
  HardwareHardwareIdBuildIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HardwareHardwareIdBuildRouteRoute,
  } as any)

const HardwareHardwareIdBootIndexRoute =
  HardwareHardwareIdBootIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HardwareHardwareIdBootRouteRoute,
  } as any)

const alternativesTTreeIdIndexRoute = alternativesTTreeIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => alternativesTTreeIdRouteRoute,
} as any)

const TreeTreeIdTestTestIdRouteRoute = TreeTreeIdTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => TreeTreeIdRouteRoute,
} as any)

const TreeTreeIdTestTestIdIndexRoute = TreeTreeIdTestTestIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreeTreeIdTestTestIdRouteRoute,
} as any)

const TreeTreeIdBuildBuildIdIndexRoute =
  TreeTreeIdBuildBuildIdIndexImport.update({
    id: '/build/$buildId/',
    path: '/build/$buildId/',
    getParentRoute: () => TreeTreeIdRouteRoute,
  } as any)

const HardwareHardwareIdTestTestIdIndexRoute =
  HardwareHardwareIdTestTestIdIndexImport.update({
    id: '/$testId/',
    path: '/$testId/',
    getParentRoute: () => HardwareHardwareIdTestRouteRoute,
  } as any)

const HardwareHardwareIdBuildBuildIdIndexRoute =
  HardwareHardwareIdBuildBuildIdIndexImport.update({
    id: '/$buildId/',
    path: '/$buildId/',
    getParentRoute: () => HardwareHardwareIdBuildRouteRoute,
  } as any)

const HardwareHardwareIdBootBootIdIndexRoute =
  HardwareHardwareIdBootBootIdIndexImport.update({
    id: '/$bootId/',
    path: '/$bootId/',
    getParentRoute: () => HardwareHardwareIdBootRouteRoute,
  } as any)

const alternativesTTreeNameBranchIndexRoute =
  alternativesTTreeNameBranchIndexImport.update({
    id: '/$treeName/$branch/',
    path: '/$treeName/$branch/',
    getParentRoute: () => alternativesTRouteRoute,
  } as any)

const alternativesTTreeIdTestTestIdRouteRoute =
  alternativesTTreeIdTestTestIdRouteImport.update({
    id: '/test/$testId',
    path: '/test/$testId',
    getParentRoute: () => alternativesTTreeIdRouteRoute,
  } as any)

const alternativesTTreeIdTestTestIdIndexRoute =
  alternativesTTreeIdTestTestIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => alternativesTTreeIdTestTestIdRouteRoute,
  } as any)

const alternativesTTreeIdBuildBuildIdIndexRoute =
  alternativesTTreeIdBuildBuildIdIndexImport.update({
    id: '/build/$buildId/',
    path: '/build/$buildId/',
    getParentRoute: () => alternativesTTreeIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRoute
    }
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRoute
    }
    '/(alternatives)/t': {
      id: '/(alternatives)/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof alternativesTRouteImport
      parentRoute: typeof rootRoute
    }
    '/build/$buildId': {
      id: '/build/$buildId'
      path: '/build/$buildId'
      fullPath: '/build/$buildId'
      preLoaderRoute: typeof BuildBuildIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/hardware/$hardwareId': {
      id: '/hardware/$hardwareId'
      path: '/$hardwareId'
      fullPath: '/hardware/$hardwareId'
      preLoaderRoute: typeof HardwareHardwareIdRouteImport
      parentRoute: typeof HardwareRouteImport
    }
    '/issue/$issueId': {
      id: '/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/issue/$issueId'
      preLoaderRoute: typeof IssueIssueIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/tree/$treeId': {
      id: '/tree/$treeId'
      path: '/$treeId'
      fullPath: '/tree/$treeId'
      preLoaderRoute: typeof TreeTreeIdRouteImport
      parentRoute: typeof TreeRouteImport
    }
    '/hardware/': {
      id: '/hardware/'
      path: '/'
      fullPath: '/hardware/'
      preLoaderRoute: typeof HardwareIndexImport
      parentRoute: typeof HardwareRouteImport
    }
    '/tree/': {
      id: '/tree/'
      path: '/'
      fullPath: '/tree/'
      preLoaderRoute: typeof TreeIndexImport
      parentRoute: typeof TreeRouteImport
    }
    '/(alternatives)/t/$treeId': {
      id: '/(alternatives)/t/$treeId'
      path: '/$treeId'
      fullPath: '/t/$treeId'
      preLoaderRoute: typeof alternativesTTreeIdRouteImport
      parentRoute: typeof alternativesTRouteImport
    }
    '/hardware/$hardwareId/boot': {
      id: '/hardware/$hardwareId/boot'
      path: '/boot'
      fullPath: '/hardware/$hardwareId/boot'
      preLoaderRoute: typeof HardwareHardwareIdBootRouteImport
      parentRoute: typeof HardwareHardwareIdRouteImport
    }
    '/hardware/$hardwareId/build': {
      id: '/hardware/$hardwareId/build'
      path: '/build'
      fullPath: '/hardware/$hardwareId/build'
      preLoaderRoute: typeof HardwareHardwareIdBuildRouteImport
      parentRoute: typeof HardwareHardwareIdRouteImport
    }
    '/hardware/$hardwareId/test': {
      id: '/hardware/$hardwareId/test'
      path: '/test'
      fullPath: '/hardware/$hardwareId/test'
      preLoaderRoute: typeof HardwareHardwareIdTestRouteImport
      parentRoute: typeof HardwareHardwareIdRouteImport
    }
    '/(alternatives)/t/': {
      id: '/(alternatives)/t/'
      path: '/'
      fullPath: '/t/'
      preLoaderRoute: typeof alternativesTIndexImport
      parentRoute: typeof alternativesTRouteImport
    }
    '/build/$buildId/': {
      id: '/build/$buildId/'
      path: '/'
      fullPath: '/build/$buildId/'
      preLoaderRoute: typeof BuildBuildIdIndexImport
      parentRoute: typeof BuildBuildIdRouteImport
    }
    '/hardware/$hardwareId/': {
      id: '/hardware/$hardwareId/'
      path: '/'
      fullPath: '/hardware/$hardwareId/'
      preLoaderRoute: typeof HardwareHardwareIdIndexImport
      parentRoute: typeof HardwareHardwareIdRouteImport
    }
    '/issue/$issueId/': {
      id: '/issue/$issueId/'
      path: '/'
      fullPath: '/issue/$issueId/'
      preLoaderRoute: typeof IssueIssueIdIndexImport
      parentRoute: typeof IssueIssueIdRouteImport
    }
    '/test/$testId/': {
      id: '/test/$testId/'
      path: '/'
      fullPath: '/test/$testId/'
      preLoaderRoute: typeof TestTestIdIndexImport
      parentRoute: typeof TestTestIdRouteImport
    }
    '/tree/$treeId/': {
      id: '/tree/$treeId/'
      path: '/'
      fullPath: '/tree/$treeId/'
      preLoaderRoute: typeof TreeTreeIdIndexImport
      parentRoute: typeof TreeTreeIdRouteImport
    }
    '/tree/$treeId/test/$testId': {
      id: '/tree/$treeId/test/$testId'
      path: '/test/$testId'
      fullPath: '/tree/$treeId/test/$testId'
      preLoaderRoute: typeof TreeTreeIdTestTestIdRouteImport
      parentRoute: typeof TreeTreeIdRouteImport
    }
    '/(alternatives)/t/$treeId/': {
      id: '/(alternatives)/t/$treeId/'
      path: '/'
      fullPath: '/t/$treeId/'
      preLoaderRoute: typeof alternativesTTreeIdIndexImport
      parentRoute: typeof alternativesTTreeIdRouteImport
    }
    '/hardware/$hardwareId/boot/': {
      id: '/hardware/$hardwareId/boot/'
      path: '/'
      fullPath: '/hardware/$hardwareId/boot/'
      preLoaderRoute: typeof HardwareHardwareIdBootIndexImport
      parentRoute: typeof HardwareHardwareIdBootRouteImport
    }
    '/hardware/$hardwareId/build/': {
      id: '/hardware/$hardwareId/build/'
      path: '/'
      fullPath: '/hardware/$hardwareId/build/'
      preLoaderRoute: typeof HardwareHardwareIdBuildIndexImport
      parentRoute: typeof HardwareHardwareIdBuildRouteImport
    }
    '/hardware/$hardwareId/test/': {
      id: '/hardware/$hardwareId/test/'
      path: '/'
      fullPath: '/hardware/$hardwareId/test/'
      preLoaderRoute: typeof HardwareHardwareIdTestIndexImport
      parentRoute: typeof HardwareHardwareIdTestRouteImport
    }
    '/tree/$treeName/$branch/': {
      id: '/tree/$treeName/$branch/'
      path: '/$treeName/$branch'
      fullPath: '/tree/$treeName/$branch'
      preLoaderRoute: typeof TreeTreeNameBranchIndexImport
      parentRoute: typeof TreeRouteImport
    }
    '/(alternatives)/t/$treeId/test/$testId': {
      id: '/(alternatives)/t/$treeId/test/$testId'
      path: '/test/$testId'
      fullPath: '/t/$treeId/test/$testId'
      preLoaderRoute: typeof alternativesTTreeIdTestTestIdRouteImport
      parentRoute: typeof alternativesTTreeIdRouteImport
    }
    '/(alternatives)/t/$treeName/$branch/': {
      id: '/(alternatives)/t/$treeName/$branch/'
      path: '/$treeName/$branch'
      fullPath: '/t/$treeName/$branch'
      preLoaderRoute: typeof alternativesTTreeNameBranchIndexImport
      parentRoute: typeof alternativesTRouteImport
    }
    '/hardware/$hardwareId/boot/$bootId/': {
      id: '/hardware/$hardwareId/boot/$bootId/'
      path: '/$bootId'
      fullPath: '/hardware/$hardwareId/boot/$bootId'
      preLoaderRoute: typeof HardwareHardwareIdBootBootIdIndexImport
      parentRoute: typeof HardwareHardwareIdBootRouteImport
    }
    '/hardware/$hardwareId/build/$buildId/': {
      id: '/hardware/$hardwareId/build/$buildId/'
      path: '/$buildId'
      fullPath: '/hardware/$hardwareId/build/$buildId'
      preLoaderRoute: typeof HardwareHardwareIdBuildBuildIdIndexImport
      parentRoute: typeof HardwareHardwareIdBuildRouteImport
    }
    '/hardware/$hardwareId/test/$testId/': {
      id: '/hardware/$hardwareId/test/$testId/'
      path: '/$testId'
      fullPath: '/hardware/$hardwareId/test/$testId'
      preLoaderRoute: typeof HardwareHardwareIdTestTestIdIndexImport
      parentRoute: typeof HardwareHardwareIdTestRouteImport
    }
    '/tree/$treeId/build/$buildId/': {
      id: '/tree/$treeId/build/$buildId/'
      path: '/build/$buildId'
      fullPath: '/tree/$treeId/build/$buildId'
      preLoaderRoute: typeof TreeTreeIdBuildBuildIdIndexImport
      parentRoute: typeof TreeTreeIdRouteImport
    }
    '/tree/$treeId/test/$testId/': {
      id: '/tree/$treeId/test/$testId/'
      path: '/'
      fullPath: '/tree/$treeId/test/$testId/'
      preLoaderRoute: typeof TreeTreeIdTestTestIdIndexImport
      parentRoute: typeof TreeTreeIdTestTestIdRouteImport
    }
    '/(alternatives)/t/$treeId/build/$buildId/': {
      id: '/(alternatives)/t/$treeId/build/$buildId/'
      path: '/build/$buildId'
      fullPath: '/t/$treeId/build/$buildId'
      preLoaderRoute: typeof alternativesTTreeIdBuildBuildIdIndexImport
      parentRoute: typeof alternativesTTreeIdRouteImport
    }
    '/(alternatives)/t/$treeId/test/$testId/': {
      id: '/(alternatives)/t/$treeId/test/$testId/'
      path: '/'
      fullPath: '/t/$treeId/test/$testId/'
      preLoaderRoute: typeof alternativesTTreeIdTestTestIdIndexImport
      parentRoute: typeof alternativesTTreeIdTestTestIdRouteImport
    }
  }
}

// Create and export the route tree

interface HardwareHardwareIdBootRouteRouteChildren {
  HardwareHardwareIdBootIndexRoute: typeof HardwareHardwareIdBootIndexRoute
  HardwareHardwareIdBootBootIdIndexRoute: typeof HardwareHardwareIdBootBootIdIndexRoute
}

const HardwareHardwareIdBootRouteRouteChildren: HardwareHardwareIdBootRouteRouteChildren =
  {
    HardwareHardwareIdBootIndexRoute: HardwareHardwareIdBootIndexRoute,
    HardwareHardwareIdBootBootIdIndexRoute:
      HardwareHardwareIdBootBootIdIndexRoute,
  }

const HardwareHardwareIdBootRouteRouteWithChildren =
  HardwareHardwareIdBootRouteRoute._addFileChildren(
    HardwareHardwareIdBootRouteRouteChildren,
  )

interface HardwareHardwareIdBuildRouteRouteChildren {
  HardwareHardwareIdBuildIndexRoute: typeof HardwareHardwareIdBuildIndexRoute
  HardwareHardwareIdBuildBuildIdIndexRoute: typeof HardwareHardwareIdBuildBuildIdIndexRoute
}

const HardwareHardwareIdBuildRouteRouteChildren: HardwareHardwareIdBuildRouteRouteChildren =
  {
    HardwareHardwareIdBuildIndexRoute: HardwareHardwareIdBuildIndexRoute,
    HardwareHardwareIdBuildBuildIdIndexRoute:
      HardwareHardwareIdBuildBuildIdIndexRoute,
  }

const HardwareHardwareIdBuildRouteRouteWithChildren =
  HardwareHardwareIdBuildRouteRoute._addFileChildren(
    HardwareHardwareIdBuildRouteRouteChildren,
  )

interface HardwareHardwareIdTestRouteRouteChildren {
  HardwareHardwareIdTestIndexRoute: typeof HardwareHardwareIdTestIndexRoute
  HardwareHardwareIdTestTestIdIndexRoute: typeof HardwareHardwareIdTestTestIdIndexRoute
}

const HardwareHardwareIdTestRouteRouteChildren: HardwareHardwareIdTestRouteRouteChildren =
  {
    HardwareHardwareIdTestIndexRoute: HardwareHardwareIdTestIndexRoute,
    HardwareHardwareIdTestTestIdIndexRoute:
      HardwareHardwareIdTestTestIdIndexRoute,
  }

const HardwareHardwareIdTestRouteRouteWithChildren =
  HardwareHardwareIdTestRouteRoute._addFileChildren(
    HardwareHardwareIdTestRouteRouteChildren,
  )

interface HardwareHardwareIdRouteRouteChildren {
  HardwareHardwareIdBootRouteRoute: typeof HardwareHardwareIdBootRouteRouteWithChildren
  HardwareHardwareIdBuildRouteRoute: typeof HardwareHardwareIdBuildRouteRouteWithChildren
  HardwareHardwareIdTestRouteRoute: typeof HardwareHardwareIdTestRouteRouteWithChildren
  HardwareHardwareIdIndexRoute: typeof HardwareHardwareIdIndexRoute
}

const HardwareHardwareIdRouteRouteChildren: HardwareHardwareIdRouteRouteChildren =
  {
    HardwareHardwareIdBootRouteRoute:
      HardwareHardwareIdBootRouteRouteWithChildren,
    HardwareHardwareIdBuildRouteRoute:
      HardwareHardwareIdBuildRouteRouteWithChildren,
    HardwareHardwareIdTestRouteRoute:
      HardwareHardwareIdTestRouteRouteWithChildren,
    HardwareHardwareIdIndexRoute: HardwareHardwareIdIndexRoute,
  }

const HardwareHardwareIdRouteRouteWithChildren =
  HardwareHardwareIdRouteRoute._addFileChildren(
    HardwareHardwareIdRouteRouteChildren,
  )

interface HardwareRouteRouteChildren {
  HardwareHardwareIdRouteRoute: typeof HardwareHardwareIdRouteRouteWithChildren
  HardwareIndexRoute: typeof HardwareIndexRoute
}

const HardwareRouteRouteChildren: HardwareRouteRouteChildren = {
  HardwareHardwareIdRouteRoute: HardwareHardwareIdRouteRouteWithChildren,
  HardwareIndexRoute: HardwareIndexRoute,
}

const HardwareRouteRouteWithChildren = HardwareRouteRoute._addFileChildren(
  HardwareRouteRouteChildren,
)

interface TreeTreeIdTestTestIdRouteRouteChildren {
  TreeTreeIdTestTestIdIndexRoute: typeof TreeTreeIdTestTestIdIndexRoute
}

const TreeTreeIdTestTestIdRouteRouteChildren: TreeTreeIdTestTestIdRouteRouteChildren =
  {
    TreeTreeIdTestTestIdIndexRoute: TreeTreeIdTestTestIdIndexRoute,
  }

const TreeTreeIdTestTestIdRouteRouteWithChildren =
  TreeTreeIdTestTestIdRouteRoute._addFileChildren(
    TreeTreeIdTestTestIdRouteRouteChildren,
  )

interface TreeTreeIdRouteRouteChildren {
  TreeTreeIdIndexRoute: typeof TreeTreeIdIndexRoute
  TreeTreeIdTestTestIdRouteRoute: typeof TreeTreeIdTestTestIdRouteRouteWithChildren
  TreeTreeIdBuildBuildIdIndexRoute: typeof TreeTreeIdBuildBuildIdIndexRoute
}

const TreeTreeIdRouteRouteChildren: TreeTreeIdRouteRouteChildren = {
  TreeTreeIdIndexRoute: TreeTreeIdIndexRoute,
  TreeTreeIdTestTestIdRouteRoute: TreeTreeIdTestTestIdRouteRouteWithChildren,
  TreeTreeIdBuildBuildIdIndexRoute: TreeTreeIdBuildBuildIdIndexRoute,
}

const TreeTreeIdRouteRouteWithChildren = TreeTreeIdRouteRoute._addFileChildren(
  TreeTreeIdRouteRouteChildren,
)

interface TreeRouteRouteChildren {
  TreeTreeIdRouteRoute: typeof TreeTreeIdRouteRouteWithChildren
  TreeIndexRoute: typeof TreeIndexRoute
  TreeTreeNameBranchIndexRoute: typeof TreeTreeNameBranchIndexRoute
}

const TreeRouteRouteChildren: TreeRouteRouteChildren = {
  TreeTreeIdRouteRoute: TreeTreeIdRouteRouteWithChildren,
  TreeIndexRoute: TreeIndexRoute,
  TreeTreeNameBranchIndexRoute: TreeTreeNameBranchIndexRoute,
}

const TreeRouteRouteWithChildren = TreeRouteRoute._addFileChildren(
  TreeRouteRouteChildren,
)

interface alternativesTTreeIdTestTestIdRouteRouteChildren {
  alternativesTTreeIdTestTestIdIndexRoute: typeof alternativesTTreeIdTestTestIdIndexRoute
}

const alternativesTTreeIdTestTestIdRouteRouteChildren: alternativesTTreeIdTestTestIdRouteRouteChildren =
  {
    alternativesTTreeIdTestTestIdIndexRoute:
      alternativesTTreeIdTestTestIdIndexRoute,
  }

const alternativesTTreeIdTestTestIdRouteRouteWithChildren =
  alternativesTTreeIdTestTestIdRouteRoute._addFileChildren(
    alternativesTTreeIdTestTestIdRouteRouteChildren,
  )

interface alternativesTTreeIdRouteRouteChildren {
  alternativesTTreeIdIndexRoute: typeof alternativesTTreeIdIndexRoute
  alternativesTTreeIdTestTestIdRouteRoute: typeof alternativesTTreeIdTestTestIdRouteRouteWithChildren
  alternativesTTreeIdBuildBuildIdIndexRoute: typeof alternativesTTreeIdBuildBuildIdIndexRoute
}

const alternativesTTreeIdRouteRouteChildren: alternativesTTreeIdRouteRouteChildren =
  {
    alternativesTTreeIdIndexRoute: alternativesTTreeIdIndexRoute,
    alternativesTTreeIdTestTestIdRouteRoute:
      alternativesTTreeIdTestTestIdRouteRouteWithChildren,
    alternativesTTreeIdBuildBuildIdIndexRoute:
      alternativesTTreeIdBuildBuildIdIndexRoute,
  }

const alternativesTTreeIdRouteRouteWithChildren =
  alternativesTTreeIdRouteRoute._addFileChildren(
    alternativesTTreeIdRouteRouteChildren,
  )

interface alternativesTRouteRouteChildren {
  alternativesTTreeIdRouteRoute: typeof alternativesTTreeIdRouteRouteWithChildren
  alternativesTIndexRoute: typeof alternativesTIndexRoute
  alternativesTTreeNameBranchIndexRoute: typeof alternativesTTreeNameBranchIndexRoute
}

const alternativesTRouteRouteChildren: alternativesTRouteRouteChildren = {
  alternativesTTreeIdRouteRoute: alternativesTTreeIdRouteRouteWithChildren,
  alternativesTIndexRoute: alternativesTIndexRoute,
  alternativesTTreeNameBranchIndexRoute: alternativesTTreeNameBranchIndexRoute,
}

const alternativesTRouteRouteWithChildren =
  alternativesTRouteRoute._addFileChildren(alternativesTRouteRouteChildren)

interface BuildBuildIdRouteRouteChildren {
  BuildBuildIdIndexRoute: typeof BuildBuildIdIndexRoute
}

const BuildBuildIdRouteRouteChildren: BuildBuildIdRouteRouteChildren = {
  BuildBuildIdIndexRoute: BuildBuildIdIndexRoute,
}

const BuildBuildIdRouteRouteWithChildren =
  BuildBuildIdRouteRoute._addFileChildren(BuildBuildIdRouteRouteChildren)

interface IssueIssueIdRouteRouteChildren {
  IssueIssueIdIndexRoute: typeof IssueIssueIdIndexRoute
}

const IssueIssueIdRouteRouteChildren: IssueIssueIdRouteRouteChildren = {
  IssueIssueIdIndexRoute: IssueIssueIdIndexRoute,
}

const IssueIssueIdRouteRouteWithChildren =
  IssueIssueIdRouteRoute._addFileChildren(IssueIssueIdRouteRouteChildren)

interface TestTestIdRouteRouteChildren {
  TestTestIdIndexRoute: typeof TestTestIdIndexRoute
}

const TestTestIdRouteRouteChildren: TestTestIdRouteRouteChildren = {
  TestTestIdIndexRoute: TestTestIdIndexRoute,
}

const TestTestIdRouteRouteWithChildren = TestTestIdRouteRoute._addFileChildren(
  TestTestIdRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRouteRouteWithChildren
  '/tree': typeof TreeRouteRouteWithChildren
  '/t': typeof alternativesTRouteRouteWithChildren
  '/build/$buildId': typeof BuildBuildIdRouteRouteWithChildren
  '/hardware/$hardwareId': typeof HardwareHardwareIdRouteRouteWithChildren
  '/issue/$issueId': typeof IssueIssueIdRouteRouteWithChildren
  '/test/$testId': typeof TestTestIdRouteRouteWithChildren
  '/tree/$treeId': typeof TreeTreeIdRouteRouteWithChildren
  '/hardware/': typeof HardwareIndexRoute
  '/tree/': typeof TreeIndexRoute
  '/t/$treeId': typeof alternativesTTreeIdRouteRouteWithChildren
  '/hardware/$hardwareId/boot': typeof HardwareHardwareIdBootRouteRouteWithChildren
  '/hardware/$hardwareId/build': typeof HardwareHardwareIdBuildRouteRouteWithChildren
  '/hardware/$hardwareId/test': typeof HardwareHardwareIdTestRouteRouteWithChildren
  '/t/': typeof alternativesTIndexRoute
  '/build/$buildId/': typeof BuildBuildIdIndexRoute
  '/hardware/$hardwareId/': typeof HardwareHardwareIdIndexRoute
  '/issue/$issueId/': typeof IssueIssueIdIndexRoute
  '/test/$testId/': typeof TestTestIdIndexRoute
  '/tree/$treeId/': typeof TreeTreeIdIndexRoute
  '/tree/$treeId/test/$testId': typeof TreeTreeIdTestTestIdRouteRouteWithChildren
  '/t/$treeId/': typeof alternativesTTreeIdIndexRoute
  '/hardware/$hardwareId/boot/': typeof HardwareHardwareIdBootIndexRoute
  '/hardware/$hardwareId/build/': typeof HardwareHardwareIdBuildIndexRoute
  '/hardware/$hardwareId/test/': typeof HardwareHardwareIdTestIndexRoute
  '/tree/$treeName/$branch': typeof TreeTreeNameBranchIndexRoute
  '/t/$treeId/test/$testId': typeof alternativesTTreeIdTestTestIdRouteRouteWithChildren
  '/t/$treeName/$branch': typeof alternativesTTreeNameBranchIndexRoute
  '/hardware/$hardwareId/boot/$bootId': typeof HardwareHardwareIdBootBootIdIndexRoute
  '/hardware/$hardwareId/build/$buildId': typeof HardwareHardwareIdBuildBuildIdIndexRoute
  '/hardware/$hardwareId/test/$testId': typeof HardwareHardwareIdTestTestIdIndexRoute
  '/tree/$treeId/build/$buildId': typeof TreeTreeIdBuildBuildIdIndexRoute
  '/tree/$treeId/test/$testId/': typeof TreeTreeIdTestTestIdIndexRoute
  '/t/$treeId/build/$buildId': typeof alternativesTTreeIdBuildBuildIdIndexRoute
  '/t/$treeId/test/$testId/': typeof alternativesTTreeIdTestTestIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareIndexRoute
  '/tree': typeof TreeIndexRoute
  '/t': typeof alternativesTIndexRoute
  '/build/$buildId': typeof BuildBuildIdIndexRoute
  '/hardware/$hardwareId': typeof HardwareHardwareIdIndexRoute
  '/issue/$issueId': typeof IssueIssueIdIndexRoute
  '/test/$testId': typeof TestTestIdIndexRoute
  '/tree/$treeId': typeof TreeTreeIdIndexRoute
  '/t/$treeId': typeof alternativesTTreeIdIndexRoute
  '/hardware/$hardwareId/boot': typeof HardwareHardwareIdBootIndexRoute
  '/hardware/$hardwareId/build': typeof HardwareHardwareIdBuildIndexRoute
  '/hardware/$hardwareId/test': typeof HardwareHardwareIdTestIndexRoute
  '/tree/$treeName/$branch': typeof TreeTreeNameBranchIndexRoute
  '/t/$treeName/$branch': typeof alternativesTTreeNameBranchIndexRoute
  '/hardware/$hardwareId/boot/$bootId': typeof HardwareHardwareIdBootBootIdIndexRoute
  '/hardware/$hardwareId/build/$buildId': typeof HardwareHardwareIdBuildBuildIdIndexRoute
  '/hardware/$hardwareId/test/$testId': typeof HardwareHardwareIdTestTestIdIndexRoute
  '/tree/$treeId/build/$buildId': typeof TreeTreeIdBuildBuildIdIndexRoute
  '/tree/$treeId/test/$testId': typeof TreeTreeIdTestTestIdIndexRoute
  '/t/$treeId/build/$buildId': typeof alternativesTTreeIdBuildBuildIdIndexRoute
  '/t/$treeId/test/$testId': typeof alternativesTTreeIdTestTestIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRouteRouteWithChildren
  '/tree': typeof TreeRouteRouteWithChildren
  '/(alternatives)/t': typeof alternativesTRouteRouteWithChildren
  '/build/$buildId': typeof BuildBuildIdRouteRouteWithChildren
  '/hardware/$hardwareId': typeof HardwareHardwareIdRouteRouteWithChildren
  '/issue/$issueId': typeof IssueIssueIdRouteRouteWithChildren
  '/test/$testId': typeof TestTestIdRouteRouteWithChildren
  '/tree/$treeId': typeof TreeTreeIdRouteRouteWithChildren
  '/hardware/': typeof HardwareIndexRoute
  '/tree/': typeof TreeIndexRoute
  '/(alternatives)/t/$treeId': typeof alternativesTTreeIdRouteRouteWithChildren
  '/hardware/$hardwareId/boot': typeof HardwareHardwareIdBootRouteRouteWithChildren
  '/hardware/$hardwareId/build': typeof HardwareHardwareIdBuildRouteRouteWithChildren
  '/hardware/$hardwareId/test': typeof HardwareHardwareIdTestRouteRouteWithChildren
  '/(alternatives)/t/': typeof alternativesTIndexRoute
  '/build/$buildId/': typeof BuildBuildIdIndexRoute
  '/hardware/$hardwareId/': typeof HardwareHardwareIdIndexRoute
  '/issue/$issueId/': typeof IssueIssueIdIndexRoute
  '/test/$testId/': typeof TestTestIdIndexRoute
  '/tree/$treeId/': typeof TreeTreeIdIndexRoute
  '/tree/$treeId/test/$testId': typeof TreeTreeIdTestTestIdRouteRouteWithChildren
  '/(alternatives)/t/$treeId/': typeof alternativesTTreeIdIndexRoute
  '/hardware/$hardwareId/boot/': typeof HardwareHardwareIdBootIndexRoute
  '/hardware/$hardwareId/build/': typeof HardwareHardwareIdBuildIndexRoute
  '/hardware/$hardwareId/test/': typeof HardwareHardwareIdTestIndexRoute
  '/tree/$treeName/$branch/': typeof TreeTreeNameBranchIndexRoute
  '/(alternatives)/t/$treeId/test/$testId': typeof alternativesTTreeIdTestTestIdRouteRouteWithChildren
  '/(alternatives)/t/$treeName/$branch/': typeof alternativesTTreeNameBranchIndexRoute
  '/hardware/$hardwareId/boot/$bootId/': typeof HardwareHardwareIdBootBootIdIndexRoute
  '/hardware/$hardwareId/build/$buildId/': typeof HardwareHardwareIdBuildBuildIdIndexRoute
  '/hardware/$hardwareId/test/$testId/': typeof HardwareHardwareIdTestTestIdIndexRoute
  '/tree/$treeId/build/$buildId/': typeof TreeTreeIdBuildBuildIdIndexRoute
  '/tree/$treeId/test/$testId/': typeof TreeTreeIdTestTestIdIndexRoute
  '/(alternatives)/t/$treeId/build/$buildId/': typeof alternativesTTreeIdBuildBuildIdIndexRoute
  '/(alternatives)/t/$treeId/test/$testId/': typeof alternativesTTreeIdTestTestIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hardware'
    | '/tree'
    | '/t'
    | '/build/$buildId'
    | '/hardware/$hardwareId'
    | '/issue/$issueId'
    | '/test/$testId'
    | '/tree/$treeId'
    | '/hardware/'
    | '/tree/'
    | '/t/$treeId'
    | '/hardware/$hardwareId/boot'
    | '/hardware/$hardwareId/build'
    | '/hardware/$hardwareId/test'
    | '/t/'
    | '/build/$buildId/'
    | '/hardware/$hardwareId/'
    | '/issue/$issueId/'
    | '/test/$testId/'
    | '/tree/$treeId/'
    | '/tree/$treeId/test/$testId'
    | '/t/$treeId/'
    | '/hardware/$hardwareId/boot/'
    | '/hardware/$hardwareId/build/'
    | '/hardware/$hardwareId/test/'
    | '/tree/$treeName/$branch'
    | '/t/$treeId/test/$testId'
    | '/t/$treeName/$branch'
    | '/hardware/$hardwareId/boot/$bootId'
    | '/hardware/$hardwareId/build/$buildId'
    | '/hardware/$hardwareId/test/$testId'
    | '/tree/$treeId/build/$buildId'
    | '/tree/$treeId/test/$testId/'
    | '/t/$treeId/build/$buildId'
    | '/t/$treeId/test/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hardware'
    | '/tree'
    | '/t'
    | '/build/$buildId'
    | '/hardware/$hardwareId'
    | '/issue/$issueId'
    | '/test/$testId'
    | '/tree/$treeId'
    | '/t/$treeId'
    | '/hardware/$hardwareId/boot'
    | '/hardware/$hardwareId/build'
    | '/hardware/$hardwareId/test'
    | '/tree/$treeName/$branch'
    | '/t/$treeName/$branch'
    | '/hardware/$hardwareId/boot/$bootId'
    | '/hardware/$hardwareId/build/$buildId'
    | '/hardware/$hardwareId/test/$testId'
    | '/tree/$treeId/build/$buildId'
    | '/tree/$treeId/test/$testId'
    | '/t/$treeId/build/$buildId'
    | '/t/$treeId/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/hardware'
    | '/tree'
    | '/(alternatives)/t'
    | '/build/$buildId'
    | '/hardware/$hardwareId'
    | '/issue/$issueId'
    | '/test/$testId'
    | '/tree/$treeId'
    | '/hardware/'
    | '/tree/'
    | '/(alternatives)/t/$treeId'
    | '/hardware/$hardwareId/boot'
    | '/hardware/$hardwareId/build'
    | '/hardware/$hardwareId/test'
    | '/(alternatives)/t/'
    | '/build/$buildId/'
    | '/hardware/$hardwareId/'
    | '/issue/$issueId/'
    | '/test/$testId/'
    | '/tree/$treeId/'
    | '/tree/$treeId/test/$testId'
    | '/(alternatives)/t/$treeId/'
    | '/hardware/$hardwareId/boot/'
    | '/hardware/$hardwareId/build/'
    | '/hardware/$hardwareId/test/'
    | '/tree/$treeName/$branch/'
    | '/(alternatives)/t/$treeId/test/$testId'
    | '/(alternatives)/t/$treeName/$branch/'
    | '/hardware/$hardwareId/boot/$bootId/'
    | '/hardware/$hardwareId/build/$buildId/'
    | '/hardware/$hardwareId/test/$testId/'
    | '/tree/$treeId/build/$buildId/'
    | '/tree/$treeId/test/$testId/'
    | '/(alternatives)/t/$treeId/build/$buildId/'
    | '/(alternatives)/t/$treeId/test/$testId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareRouteRoute: typeof HardwareRouteRouteWithChildren
  TreeRouteRoute: typeof TreeRouteRouteWithChildren
  alternativesTRouteRoute: typeof alternativesTRouteRouteWithChildren
  BuildBuildIdRouteRoute: typeof BuildBuildIdRouteRouteWithChildren
  IssueIssueIdRouteRoute: typeof IssueIssueIdRouteRouteWithChildren
  TestTestIdRouteRoute: typeof TestTestIdRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareRouteRoute: HardwareRouteRouteWithChildren,
  TreeRouteRoute: TreeRouteRouteWithChildren,
  alternativesTRouteRoute: alternativesTRouteRouteWithChildren,
  BuildBuildIdRouteRoute: BuildBuildIdRouteRouteWithChildren,
  IssueIssueIdRouteRoute: IssueIssueIdRouteRouteWithChildren,
  TestTestIdRouteRoute: TestTestIdRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hardware",
        "/tree",
        "/(alternatives)/t",
        "/build/$buildId",
        "/issue/$issueId",
        "/test/$testId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hardware": {
      "filePath": "hardware/route.tsx",
      "children": [
        "/hardware/$hardwareId",
        "/hardware/"
      ]
    },
    "/tree": {
      "filePath": "tree/route.tsx",
      "children": [
        "/tree/$treeId",
        "/tree/",
        "/tree/$treeName/$branch/"
      ]
    },
    "/(alternatives)/t": {
      "filePath": "(alternatives)/t/route.tsx",
      "children": [
        "/(alternatives)/t/$treeId",
        "/(alternatives)/t/",
        "/(alternatives)/t/$treeName/$branch/"
      ]
    },
    "/build/$buildId": {
      "filePath": "build/$buildId/route.tsx",
      "children": [
        "/build/$buildId/"
      ]
    },
    "/hardware/$hardwareId": {
      "filePath": "hardware/$hardwareId/route.tsx",
      "parent": "/hardware",
      "children": [
        "/hardware/$hardwareId/boot",
        "/hardware/$hardwareId/build",
        "/hardware/$hardwareId/test",
        "/hardware/$hardwareId/"
      ]
    },
    "/issue/$issueId": {
      "filePath": "issue/$issueId/route.tsx",
      "children": [
        "/issue/$issueId/"
      ]
    },
    "/test/$testId": {
      "filePath": "test/$testId/route.tsx",
      "children": [
        "/test/$testId/"
      ]
    },
    "/tree/$treeId": {
      "filePath": "tree/$treeId/route.tsx",
      "parent": "/tree",
      "children": [
        "/tree/$treeId/",
        "/tree/$treeId/test/$testId",
        "/tree/$treeId/build/$buildId/"
      ]
    },
    "/hardware/": {
      "filePath": "hardware/index.tsx",
      "parent": "/hardware"
    },
    "/tree/": {
      "filePath": "tree/index.tsx",
      "parent": "/tree"
    },
    "/(alternatives)/t/$treeId": {
      "filePath": "(alternatives)/t/$treeId/route.tsx",
      "parent": "/(alternatives)/t",
      "children": [
        "/(alternatives)/t/$treeId/",
        "/(alternatives)/t/$treeId/test/$testId",
        "/(alternatives)/t/$treeId/build/$buildId/"
      ]
    },
    "/hardware/$hardwareId/boot": {
      "filePath": "hardware/$hardwareId/boot/route.tsx",
      "parent": "/hardware/$hardwareId",
      "children": [
        "/hardware/$hardwareId/boot/",
        "/hardware/$hardwareId/boot/$bootId/"
      ]
    },
    "/hardware/$hardwareId/build": {
      "filePath": "hardware/$hardwareId/build/route.tsx",
      "parent": "/hardware/$hardwareId",
      "children": [
        "/hardware/$hardwareId/build/",
        "/hardware/$hardwareId/build/$buildId/"
      ]
    },
    "/hardware/$hardwareId/test": {
      "filePath": "hardware/$hardwareId/test/route.tsx",
      "parent": "/hardware/$hardwareId",
      "children": [
        "/hardware/$hardwareId/test/",
        "/hardware/$hardwareId/test/$testId/"
      ]
    },
    "/(alternatives)/t/": {
      "filePath": "(alternatives)/t/index.tsx",
      "parent": "/(alternatives)/t"
    },
    "/build/$buildId/": {
      "filePath": "build/$buildId/index.tsx",
      "parent": "/build/$buildId"
    },
    "/hardware/$hardwareId/": {
      "filePath": "hardware/$hardwareId/index.tsx",
      "parent": "/hardware/$hardwareId"
    },
    "/issue/$issueId/": {
      "filePath": "issue/$issueId/index.tsx",
      "parent": "/issue/$issueId"
    },
    "/test/$testId/": {
      "filePath": "test/$testId/index.tsx",
      "parent": "/test/$testId"
    },
    "/tree/$treeId/": {
      "filePath": "tree/$treeId/index.tsx",
      "parent": "/tree/$treeId"
    },
    "/tree/$treeId/test/$testId": {
      "filePath": "tree/$treeId/test/$testId/route.tsx",
      "parent": "/tree/$treeId",
      "children": [
        "/tree/$treeId/test/$testId/"
      ]
    },
    "/(alternatives)/t/$treeId/": {
      "filePath": "(alternatives)/t/$treeId/index.tsx",
      "parent": "/(alternatives)/t/$treeId"
    },
    "/hardware/$hardwareId/boot/": {
      "filePath": "hardware/$hardwareId/boot/index.tsx",
      "parent": "/hardware/$hardwareId/boot"
    },
    "/hardware/$hardwareId/build/": {
      "filePath": "hardware/$hardwareId/build/index.tsx",
      "parent": "/hardware/$hardwareId/build"
    },
    "/hardware/$hardwareId/test/": {
      "filePath": "hardware/$hardwareId/test/index.tsx",
      "parent": "/hardware/$hardwareId/test"
    },
    "/tree/$treeName/$branch/": {
      "filePath": "tree/$treeName/$branch/index.tsx",
      "parent": "/tree"
    },
    "/(alternatives)/t/$treeId/test/$testId": {
      "filePath": "(alternatives)/t/$treeId/test/$testId/route.tsx",
      "parent": "/(alternatives)/t/$treeId",
      "children": [
        "/(alternatives)/t/$treeId/test/$testId/"
      ]
    },
    "/(alternatives)/t/$treeName/$branch/": {
      "filePath": "(alternatives)/t/$treeName/$branch/index.tsx",
      "parent": "/(alternatives)/t"
    },
    "/hardware/$hardwareId/boot/$bootId/": {
      "filePath": "hardware/$hardwareId/boot/$bootId/index.tsx",
      "parent": "/hardware/$hardwareId/boot"
    },
    "/hardware/$hardwareId/build/$buildId/": {
      "filePath": "hardware/$hardwareId/build/$buildId/index.tsx",
      "parent": "/hardware/$hardwareId/build"
    },
    "/hardware/$hardwareId/test/$testId/": {
      "filePath": "hardware/$hardwareId/test/$testId/index.tsx",
      "parent": "/hardware/$hardwareId/test"
    },
    "/tree/$treeId/build/$buildId/": {
      "filePath": "tree/$treeId/build/$buildId/index.tsx",
      "parent": "/tree/$treeId"
    },
    "/tree/$treeId/test/$testId/": {
      "filePath": "tree/$treeId/test/$testId/index.tsx",
      "parent": "/tree/$treeId/test/$testId"
    },
    "/(alternatives)/t/$treeId/build/$buildId/": {
      "filePath": "(alternatives)/t/$treeId/build/$buildId/index.tsx",
      "parent": "/(alternatives)/t/$treeId"
    },
    "/(alternatives)/t/$treeId/test/$testId/": {
      "filePath": "(alternatives)/t/$treeId/test/$testId/index.tsx",
      "parent": "/(alternatives)/t/$treeId/test/$testId"
    }
  }
}
ROUTE_MANIFEST_END */
