"""Management command to validate backend environment setup.

This is intended for manual validation when running inside Docker with:
    docker compose run --rm backend ...
"""

import os
import socket
import tempfile
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connections
from django.db.utils import OperationalError

from redis import Redis
from redis.exceptions import RedisError

from kernelCI_app.helpers.email import smtp_send_email, smtp_setup_connection


DEFAULT_REDIS_TIMEOUT_SECONDS = 5


class Command(BaseCommand):
    help = (
        "Validate backend environment dependencies: database, redis, email/SMTP,"
        " storage/volume permissions, and env/secrets presence."
        " Optional test email send is available."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--check-db",
            action="store_true",
            help="Check database connectivity for selected aliases (default: default)",
        )
        parser.add_argument(
            "--database-alias",
            action="append",
            default=None,
            help="Database alias to check. Can be repeated or passed comma-separated.",
        )
        parser.add_argument(
            "--check-redis",
            action="store_true",
            help="Check redis connectivity.",
        )
        parser.add_argument(
            "--check-email",
            action="store_true",
            help="Check email backend configuration and SMTP connection.",
        )
        parser.add_argument(
            "--check-storage",
            action="store_true",
            help="Check required backend directories and mounted volumes are writable.",
        )
        parser.add_argument(
            "--check-env",
            action="store_true",
            help="Check required environment variables and secrets presence.",
        )
        parser.add_argument(
            "--send-test-email",
            action="store_true",
            help="Send a real test email (requires --to-email).",
        )
        parser.add_argument(
            "--to-email",
            type=str,
            help="Recipient email address for --send-test-email",
        )
        parser.add_argument(
            "--cc",
            type=str,
            default="",
            help="Optional CC recipient list for --send-test-email (comma-separated)",
        )
        parser.add_argument(
            "--subject",
            type=str,
            default="KernelCI email check",
            help="Email subject for --send-test-email",
        )
        parser.add_argument(
            "--body",
            type=str,
            default=(
                "This is a test message generated by the verify_env command."
                " If you received this email, SMTP env settings are working."
            ),
            help="Email body for --send-test-email",
        )
        parser.add_argument(
            "--redis-host",
            type=str,
            default=None,
            help="Redis host override (optional). Defaults to REDIS_HOST env variable.",
        )
        parser.add_argument(
            "--redis-port",
            type=int,
            default=None,
            help="Redis port override (optional). Defaults to 6379.",
        )
        parser.add_argument(
            "--redis-db",
            type=int,
            default=None,
            help="Redis DB override (optional). Defaults to 0.",
        )
        parser.add_argument(
            "--redis-password",
            type=str,
            default=None,
            help="Redis password override (optional)",
        )
        parser.add_argument(
            "--create-dirs",
            action="store_true",
            help="Create missing directories during storage checks (default: report as failure)",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        selected_checks = self._collect_selected_checks(options)
        self._warn_send_test_email(selected_checks, options)

        self.stdout.write("Starting environment verification...\n")

        results: list[tuple[str, bool, str]] = []
        check_map = {
            "db": lambda: self._check_databases(options),
            "redis": lambda: [self._check_redis(options)],
            "email": lambda: self._check_email_configuration(options),
            "storage": lambda: self._check_storage_paths(options),
            "env": self._check_environment_values,
        }

        for check_name, gather in check_map.items():
            if check_name in selected_checks:
                results.extend(gather())

        if options.get("send_test_email"):
            results.append(self._send_email_test(options))

        failures = [result for result in results if not result[1]]
        self._print_summary(results)

        if failures:
            messages = [entry[2] for entry in failures]
            raise CommandError(
                "Environment verification failed:\n" + "\n".join(messages)
            )

        self.stdout.write(self.style.SUCCESS("Environment verification passed."))

    def _warn_send_test_email(
        self,
        selected_checks: set[str],
        options: dict[str, Any],
    ) -> None:
        if "email" not in selected_checks or not options.get("send_test_email"):
            return
        if not options.get("to_email"):
            raise CommandError("--send-test-email requires --to-email to be set.")
        self.stdout.write(
            "WARNING: This will attempt to send a real email using the "
            "configured SMTP settings.\n"
        )

    def _check_databases(self, options: dict[str, Any]) -> list[tuple[str, bool, str]]:
        results: list[tuple[str, bool, str]] = []
        for alias in self._collect_database_aliases(
            options.get("database_alias") or []
        ):
            results.extend(self._check_database(alias))
        return results

    def _collect_selected_checks(self, options: dict[str, Any]) -> set[str]:
        explicit = (
            options.get("check_db")
            or options.get("check_redis")
            or options.get("check_email")
            or options.get("check_storage")
            or options.get("check_env")
            or options.get("send_test_email")
        )

        selected: set[str] = set()

        if not explicit:
            selected.update(["db", "redis", "email", "storage", "env"])
            return selected

        if options.get("check_db"):
            selected.add("db")
        if options.get("check_redis"):
            selected.add("redis")
        if options.get("check_email") or options.get("send_test_email"):
            selected.add("email")
        if options.get("check_storage"):
            selected.add("storage")
        if options.get("check_env"):
            selected.add("env")

        return selected

    def _collect_database_aliases(self, raw_aliases: list[str]) -> list[str]:
        aliases: list[str] = []
        for value in raw_aliases:
            aliases.extend(
                [
                    candidate.strip()
                    for candidate in value.split(",")
                    if candidate.strip()
                ]
            )

        return aliases or ["default"]

    def _check_database(self, alias: str) -> list[tuple[str, bool, str]]:
        if alias not in settings.DATABASES:
            return [
                (
                    f"db:{alias}",
                    False,
                    f"Database alias '{alias}' is not defined in settings",
                )
            ]

        connection = connections[alias]

        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT 1")
                row = cursor.fetchone()
            return [
                (
                    f"db:{alias}",
                    True,
                    f"Connected to DB alias '{alias}' and got result: {row}",
                )
            ]
        except OperationalError as err:
            return [
                (f"db:{alias}", False, f"Failed connecting DB alias '{alias}': {err}")
            ]
        except Exception as err:
            return [
                (
                    f"db:{alias}",
                    False,
                    f"Unexpected DB error for alias '{alias}': {err}",
                )
            ]

    def _check_redis(self, options: dict[str, Any]) -> tuple[str, bool, str]:
        host = options.get("redis_host") or os.getenv("REDIS_HOST", "localhost")
        port = options.get("redis_port")
        db = options.get("redis_db")
        password = options.get("redis_password") or os.getenv("REDIS_PASSWORD")

        try:
            if port is None:
                port = int(os.getenv("REDIS_PORT", "6379"))
            else:
                port = int(port)
            if db is None:
                db = int(os.getenv("REDIS_DB", "0"))
            else:
                db = int(db)

            client = Redis(
                host=host,
                port=port,
                db=db,
                password=password,
                socket_connect_timeout=DEFAULT_REDIS_TIMEOUT_SECONDS,
                socket_timeout=DEFAULT_REDIS_TIMEOUT_SECONDS,
            )
            pong = client.ping()
            return (
                "redis",
                bool(pong),
                f"Connected to Redis at {host}:{port}/{db} (PING={pong})",
            )
        except (OSError, RedisError, ConnectionRefusedError, socket.gaierror) as err:
            return (
                "redis",
                False,
                f"Failed connecting to Redis at {host}:{port}/{db}: {err}",
            )
        except ValueError as err:
            return (
                "redis",
                False,
                f"Invalid Redis configuration for {host}:{port}/{db}: {err}",
            )

    def _check_email_configuration(
        self, options: dict[str, Any]
    ) -> list[tuple[str, bool, str]]:
        email_backend = getattr(settings, "EMAIL_BACKEND", "")
        is_smtp_backend = "smtp" in email_backend

        results = [
            (
                "email:config",
                bool(email_backend),
                f"EMAIL_BACKEND={email_backend or '<unset>'}",
            ),
            (
                "email:server",
                bool(
                    getattr(settings, "EMAIL_HOST", "")
                    and getattr(settings, "EMAIL_PORT", "")
                ),
                (
                    f"EMAIL_HOST={getattr(settings, 'EMAIL_HOST', '<unset>')} "
                    f"EMAIL_PORT={getattr(settings, 'EMAIL_PORT', '<unset>')}"
                ),
            ),
            (
                "email:sender",
                bool(getattr(settings, "EMAIL_HOST_USER", "")),
                f"EMAIL_HOST_USER={'<unset>' if not settings.EMAIL_HOST_USER else settings.EMAIL_HOST_USER}",
            ),
            (
                "email:password",
                (not is_smtp_backend)
                or bool(getattr(settings, "EMAIL_HOST_PASSWORD", "")),
                (
                    "EMAIL_HOST_PASSWORD is set"
                    if getattr(settings, "EMAIL_HOST_PASSWORD", "")
                    else (
                        "EMAIL_HOST_PASSWORD is empty (SMTP authentication likely fails)"
                        if is_smtp_backend
                        else "EMAIL_HOST_PASSWORD skipped for non-SMTP backend"
                    )
                ),
            ),
        ]

        if options.get("check_email"):
            results.extend(self._check_smtp_connection())

        return results

    def _check_storage_paths(
        self, options: dict[str, Any]
    ) -> list[tuple[str, bool, str]]:
        required_paths = self._collect_storage_paths()
        results: list[tuple[str, bool, str]] = []
        create_dirs = options.get("create_dirs", False)

        for label, path in required_paths:
            try:
                if os.path.splitext(path)[1]:
                    parent_dir = os.path.dirname(path)
                    if not parent_dir:
                        parent_dir = "."
                    path_to_check = parent_dir
                else:
                    path_to_check = path

                was_created = False
                if not os.path.exists(path_to_check):
                    if create_dirs:
                        os.makedirs(path_to_check, exist_ok=True)
                        was_created = True
                    else:
                        results.append(
                            (
                                f"storage:{label}",
                                False,
                                f"Path does not exist: {path_to_check} (use --create-dirs to create)",
                            )
                        )
                        continue

                if not os.access(path_to_check, os.W_OK):
                    results.append(
                        (
                            f"storage:{label}",
                            False,
                            f"Path not writable: {path_to_check}",
                        )
                    )
                    continue

                with tempfile.NamedTemporaryFile(
                    dir=path_to_check, prefix=".verify-env-", delete=True
                ):
                    pass

                msg = f"{path_to_check} exists and is writable"
                if was_created:
                    msg += " (created by --create-dirs)"

                results.append(
                    (
                        f"storage:{label}",
                        True,
                        msg,
                    )
                )
            except Exception as err:
                results.append(
                    (
                        f"storage:{label}",
                        False,
                        f"Unable to validate path '{path_to_check}': {err}",
                    )
                )

        return results

    def _collect_storage_paths(self) -> list[tuple[str, str]]:
        cache_path = settings.DATABASES["cache"]["NAME"]
        notifications_path = settings.DATABASES["notifications"]["NAME"]
        storage_paths = [
            ("BACKEND_DATA_DIR", settings.BACKEND_DATA_DIR),
            ("BACKEND_VOLUME_DIR", settings.BACKEND_VOLUME_DIR),
            (
                "notifs-subscriptions",
                os.path.join(
                    settings.BACKEND_DATA_DIR, "notifications", "subscriptions"
                ),
            ),
        ]

        for alias, db_name in (
            ("cache_sqlite", cache_path),
            ("notifications_sqlite", notifications_path),
        ):
            if db_name and db_name != ":memory:":
                storage_paths.append((f"sqlite:{alias}", db_name))

        return storage_paths

    def _check_environment_values(self) -> list[tuple[str, bool, str]]:
        checks = [
            (
                "env:DJANGO_SECRET_KEY",
                bool(os.environ.get("DJANGO_SECRET_KEY")),
                (
                    "DJANGO_SECRET_KEY is set"
                    if os.environ.get("DJANGO_SECRET_KEY")
                    else "DJANGO_SECRET_KEY is not set (using default insecure key)"
                ),
            ),
            (
                "env:DB_PASSWORD",
                self._environment_secret_present("DB_PASSWORD"),
                self._environment_secret_message("DB_PASSWORD"),
            ),
        ]

        email_checks = [
            (
                "env:EMAIL_HOST_PASSWORD",
                (
                    self._environment_secret_present("EMAIL_HOST_PASSWORD")
                    if "smtp" in str(getattr(settings, "EMAIL_BACKEND", ""))
                    else True
                ),
                (
                    self._environment_secret_message("EMAIL_HOST_PASSWORD")
                    if "smtp" in str(getattr(settings, "EMAIL_BACKEND", ""))
                    else "EMAIL_HOST_PASSWORD skipped for non-SMTP backend"
                ),
            )
        ]

        checks.extend(email_checks)

        checks.append(
            (
                "env:DISCORD_WEBHOOK_URL",
                True,
                (
                    "DISCORD_WEBHOOK_URL is set"
                    if os.environ.get("DISCORD_WEBHOOK_URL")
                    else "DISCORD_WEBHOOK_URL is not set (notifications to Discord will be skipped)"
                ),
            )
        )

        return checks

    def _environment_secret_present(self, env_var: str) -> bool:
        value = os.environ.get(env_var)
        if value is not None and value != "":
            return True

        file_var = os.environ.get(f"{env_var}_FILE")
        if not file_var:
            return False

        return os.path.isfile(file_var) and os.access(file_var, os.R_OK)

    def _environment_secret_message(self, env_var: str) -> str:
        if os.environ.get(env_var):
            return f"{env_var} is set"

        secret_file = os.environ.get(f"{env_var}_FILE")
        if secret_file:
            if os.path.isfile(secret_file) and os.access(secret_file, os.R_OK):
                return f"{env_var} loaded from file {secret_file}"
            return f"{env_var}_FILE is set but unreadable/missing: {secret_file}"

        return f"{env_var} is not set"

    def _check_smtp_connection(self) -> list[tuple[str, bool, str]]:
        try:
            service = smtp_setup_connection()
            service.open()
            service.close()
            return [("email:smtp", True, "SMTP backend opened successfully")]
        except Exception as err:
            return [("email:smtp", False, f"SMTP backend connection failed: {err}")]

    def _send_email_test(self, options: dict[str, Any]) -> tuple[str, bool, str]:
        try:
            service = smtp_setup_connection()
            sender = (
                f"KernelCI Dashboard <{settings.EMAIL_HOST_USER}>"
                if getattr(settings, "EMAIL_HOST_USER", "")
                else "KernelCI Dashboard <kernelci-noreply@localhost>"
            )
            cc = options.get("cc") or ""
            smtp_send_email(
                connection=service,
                sender_email=sender,
                to=options["to_email"],
                subject=options["subject"],
                message_text=options["body"],
                cc=cc,
                reply_to=None,
                in_reply_to=None,
            )
            return ("email:test", True, "Test email sent successfully")
        except Exception as err:
            return ("email:test", False, f"Test email send failed: {err}")

    def _print_summary(self, results: list[tuple[str, bool, str]]) -> None:
        self.stdout.write("\nVerification results:")
        for item, ok, message in results:
            if ok:
                self.stdout.write(f"  {self.style.SUCCESS('PASS')} {item}: {message}")
            else:
                self.stdout.write(f"  {self.style.ERROR('FAIL')} {item}: {message}")
